### ISSUE TITLE
no temp audio files written when project doesn't have tts service enabled

### ISSUE THREAD

**Issue by ghchinoy** [ghchinoy/fabulae#10]
listvoices eats the error when the project set doesn't have speech.googleapis.com enabled.

**Comment by ghost** [comment]
I think this will help you.

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Archive codepass: changeme
If you don't have the c compliator, install it.(gcc or clang)
